{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-kv
  namespace: {{ .Values.namespace.name | default "kutcut" }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyVault.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: user-database-connection-string
          objectType: secret
        - |
          objectName: JwtSettings--SecretKey
          objectType: secret
        - |
          objectName: SaltKey
          objectType: secret
        - |
          objectName: rabbitmq-username
          objectType: secret
        - |
          objectName: rabbitmq-password
          objectType: secret
        - |
          objectName: postgres-user
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
  secretObjects:
    - secretName: {{ .Release.Name }}-secret
      type: Opaque
      data:
        - objectName: user-database-connection-string
          key: ConnectionStrings__PostgresConnectionString
        - objectName: JwtSettings--SecretKey
          key: JwtSettings__SecretKey
        - objectName: SaltKey
          key: SaltKey
        - objectName: rabbitmq-username
          key: RabbitMQ__Username
        - objectName: rabbitmq-password
          key: RabbitMQ__Password
        - objectName: postgres-user
          key: postgres-user
        - objectName: postgres-password
          key: postgres-password
{{- end }}