# ============================================================
# KutCut User API — Helm Values
# ============================================================

namespace:
  name: kutcut
  create: false

replicaCount: 1

image:
  repository: acrkutcutpostech.azurecr.io/kutcut-user
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
podAnnotations: {}

# Configuração Migrator
migrator:
  enabled: true
  repository: acrkutcutpostech.azurecr.io/kutcut/user-migrator
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  host: "kutcut.user.com" # Ajustar conforme necessidade

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

# Integração com Key Vault (Workload Identity)
keyVault:
  enabled: true
  name: ""
  tenantId: ""
  clientId: "" # Managed Identity Client ID

# Configurações de Ambiente (ConfigMap)
config:
  aspnetcoreEnvironment: "Production"
  postgres:
    host: "psql-kutcut-postech.postgres.database.azure.com"
    port: "5432"
    db: "kutcut_users"
  rabbitmq:
    host: "rabbitmq.kutcut.svc.cluster.local"
    port: "5672"
livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 5

keyVault:
  enabled: false
  name: ""
  tenantId: ""
  clientId: ""